name: Hello world Workflow


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  hello:
    runs-on: ubtunu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello World"
        shell: bash
  
  goodbye:
    runs-on: ubtunu-latest
    steps:
      - name: Goodbye World
        run: echo "Goodbye World"
        shell: bash
